# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: ESS Data Management and Scientific Computing Summer School
author: Data Management and Scientific Computing
# logo: logo.png
copyright: "2026"

parse:
  myst_enable_extensions:
    # - amsmath
    - colon_fence
    # - deflist
    - dollarmath
    # - html_admonition
    - html_image
    - linkify
    # - replacements
    # - smartquotes
    - substitution
    - tasklist

# See https://jupyterbook.org/content/execute.html
execute:
  timeout: -1
  execute_notebooks: auto
  allow_errors: false
  stderr_output: "error"
  exclude_patterns:
    - '3-mcstas/Talk.ipynb'
    - '6-scicat/9-exercise.ipynb'
    - '6-scicat/upload.ipynb'
    - '6-scicat/workbooks/*'

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/ess-dmsc-dram/dmsc-school  # Online location of your book
  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: main  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  favicon: "images/favicon.ico"  # A path to a favicon image
  use_issues_button: true
  use_repository_button: true

sphinx:
  extra_extensions:
    - sphinxcontrib.mermaid
  config:
    nb_execution_show_tb: True
    suppress_warnings:
      - "mystnb.mime_priority"  # From linkcheck. Mimetypes shouldn't affect link checking
      - "mystnb.unknown_mime_type"  # From plotly. The output looks fine, so this seems safe to ignore.
      - "myst.xref_missing"
      - "misc.highlighting_failure"  # This is needed to suppress warnings from the pygments highlighter associated with sciline "an error at token: '→'. Retrying in relaxed mode."
    linkcheck_ignore:
      # Seems to be too unreliable
      - 'https?://www\.crystallography\.net/'
      - 'https://people.sc.fsu.edu/~jburkardt/data/csv/csv.html'
    linkcheck_anchors_ignore_for_url:
      # These are redirected to a URL with a concrete version,
      # linkcheck cannot resolve anchors with this redirect.
      # This means that we have to manually check the anchors!
      - 'https?://docs\.easydiffraction\.org/lib/latest'
      - 'https?://easyscience\.github\.io/diffraction-lib/latest'

exclude_patterns:
  - 'article/article.md'
  - '.pixi/*'

only_build_toc_files: true
