[workspace]
name = "dmsc-school"
channels = ["conda-forge"]
requires-pixi = ">=0.71.2"
platforms = [
  { platform = "linux-64" },
  { platform = "win-64" },
  # Scipp does not support older OSX versions.
  { platform = "osx-64", macos = "14.0" },
  { platform = "osx-arm64", macos = "14.0" },
]

[dependencies]
python = "3.12.*"
corner = ">=2.2"
dynesty = ">=2.1"
easydiffraction = "=0.6"
easyscience = "=1.3"
emcee = ">=3.1"
graphviz = ">=13.1.2"
h5py = ">=3.13"
ipympl = ">=0.9"
ipython = ">=9.14"
ipywidgets = ">=8.1"
jupyter-book = ">=1,<2"
jupyterlab = ">=4.5"
jupyterquiz = ">=2.9"
matplotlib = ">=3.10"
mcstas = ">=3.7.5"
mcstasscript = ">=0.0.84"
mcstastox = ">=0.0.12"
mpltoolbox = ">=26.2.0"
numpy = "*"  # This currently installs v1 because of easyscience, need to update!
pandas = ">=3.0.3"
plopp = ">=26.5"
pooch = ">=1.9"
pytest = ">=8.4"
python-graphviz = ">=0.21"
pythreejs = ">=2.4"
scipp = ">=26.3.1"
scippneutron = ">=26.5"
scippnexus = ">=26.1.1"
scipy = ">=1.17.1"
scitacean = ">=26.2"
sphinxcontrib-mermaid = ">=1.0"

[tasks.build]
cmd = "jupyter-book build -W --keep-going ."
description = "Build the book"
cwd = "./"

[tasks.linkcheck]
cmd = "jupyter-book build -W --keep-going --builder linkcheck ."
description = "Check links in the book"
cwd = "./"
