name: deploy-book

on:
  push:
    branches:
    - main
  pull_request:
  workflow_dispatch:
    inputs:
      deploy:
        description: 'Deploy book'
        required: true
        type: boolean
      linkcheck:
        description: 'Check links'
        default: true
        type: boolean

jobs:
  formatting:
    name: Formatting and static analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: pre-commit/action@v3.0.1
        with:
          extra_args: --all-files
      - uses: pre-commit-ci/lite-action@v1.1.0
        if: always()
        with:
          msg: Apply automatic formatting

  build-book:
    needs: formatting
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}  # required for conda env
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v7

      - name: Setup python
        uses: prefix-dev/setup-pixi@v0.9.4
        with:
          pixi-version: v0.72.0
          frozen: true

      - name: Build the book
        run: |
          pixi run build

      - uses: actions/upload-artifact@v7
        with:
          name: dmsc-school-book
          path: ./_build/html

      - name: Check links
        if: github.event_name != 'workflow_dispatch' || inputs.linkcheck
        run: |
          pixi run linkcheck

  deploy-book:
    needs: [build-book]
    runs-on: ubuntu-latest
    if: (github.event_name == 'push' && github.ref_name == 'main') || inputs.deploy

    steps:
      - uses: actions/download-artifact@v8
      - name: Upload to GH pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dmsc-school-book
          force_orphan: true
