name: Update notebooks

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'If not set, the current branch will be used.'
        default: ''
        required: false
        type: string

jobs:
  update:
    name: Update notebooks
    runs-on: 'ubuntu-24.04'

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch == '' && github.ref_name || inputs.branch }}
          path: source
      - uses: actions/checkout@v4
        with:
          name: ess-dmsc-dram/dmsc-school-notebooks
          path: notebooks

      - uses: actions/setup-python@v5

      - run: |
          cd source
          python strip_solutions.py ../notebooks
          cd ..

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          path: notebooks
          commit-message: 'Update notebooks'
          title: 'Update notebooks'
          body: 'This PR updates the notebooks.'
          branch: update-notebooks


